#!/bin/bash

# If I'm a symlink, I need to CD to where I was declared
if [[ -L $0 ]]; then
  cd "$(dirname "$(readlink $0)")"
else
  cd "$(dirname "$0")"
fi

# Get a random number between 1 to 2
LC_CTYPE=C # Supposedly fix tr usage with urandom output http://bit.ly/1r7e9f4
RANDOM_NUMBER=$(cat /dev/urandom | tr -dc '1-2' | fold -w 1 | head -n 1)

# Check if afplay exists, use aplay by default
cmd='aplay'

afplay -h > /dev/null 2>&1
AFP=$?

if [[ $AFP -eq 0 ]]; then
    cmd='afplay'
fi

# Play the sound!
$cmd ./sounds/work-complete$RANDOM_NUMBER.wav
