#!/bin/bash

# If I'm a symlink, I need to CD to where I was declared
if [[ -L $0 ]]; then
  cd "$(dirname "$(readlink $0)")"
else
  cd "$(dirname "$0")"
fi

# Get a random number between 1 to 2
RANDOM_NUMBER=$(( ( RANDOM % 2 )  + 1 ))

# Check if afplay exists, use aplay by default
cmd='aplay'

if hash afplay 2>/dev/null; then
  cmd='afplay'
fi

# Play the sound!
$cmd ./sounds/death$RANDOM_NUMBER.wav
